// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function DisableVPN() {
  return window['go']['main']['App']['DisableVPN']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function EnableVPN() {
  return window['go']['main']['App']['EnableVPN']();
}

export function GetProxyAddresses() {
  return window['go']['main']['App']['GetProxyAddresses']();
}

export function GetProxySettings() {
  return window['go']['main']['App']['GetProxySettings']();
}

export function GetQuickSettings() {
  return window['go']['main']['App']['GetQuickSettings']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function OpenWebDashboard() {
  return window['go']['main']['App']['OpenWebDashboard']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RestartClient() {
  return window['go']['main']['App']['RestartClient']();
}

export function SelectServer(arg1) {
  return window['go']['main']['App']['SelectServer'](arg1);
}

export function UpdateProxySettings(arg1) {
  return window['go']['main']['App']['UpdateProxySettings'](arg1);
}

export function UpdateQuickSettings(arg1) {
  return window['go']['main']['App']['UpdateQuickSettings'](arg1);
}
